extends: stylelint-config-standard
plugins:
  - stylelint-scss
  - stylelint-order

rules:
  indentation: [ 2, { ignore: [param, value] } ]
  selector-list-comma-newline-after: null
  rule-empty-line-before: null
  at-rule-empty-line-before: null
  declaration-colon-newline-after: null
  declaration-empty-line-before: [ never, { ignore: [after-declaration] } ]
  number-no-trailing-zeros: null

  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  no-descending-specificity: null
